# Generated by Django 5.2.3 on 2025-07-09 23:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_request_reset',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_exams',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='period_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='period_start',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
