# Generated by Django 5.2.3 on 2025-07-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('matematicas', 'Matemáticas'), ('fisica', 'Física'), ('quimica', 'Química'), ('biologia', 'Biología'), ('informatica', 'Informática'), ('medicina', 'Medicina'), ('otro', 'Otro')], default='otro', max_length=20, null=True),
        ),
    ]
