# Generated by Django 5.2.3 on 2025-07-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Gratuito'), ('premium', 'Premium')], max_length=10, unique=True)),
                ('daily_ia_requests', models.PositiveIntegerField(default=5, verbose_name='Preguntas diarias')),
                ('daily_exams', models.PositiveIntegerField(default=5, verbose_name='Exámenes diarios')),
                ('period_days', models.PositiveIntegerField(default=30, verbose_name='Duración del periodo (días)')),
            ],
        ),
    ]
