# Generated by Django 5.2.3 on 2025-07-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_planconfig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='daily_exams',
            new_name='daily_requests',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='daily_ia_requests',
            new_name='total_requests',
        ),
        migrations.RemoveField(
            model_name='planconfig',
            name='daily_exams',
        ),
        migrations.RemoveField(
            model_name='planconfig',
            name='daily_ia_requests',
        ),
        migrations.RemoveField(
            model_name='planconfig',
            name='period_days',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='period_days',
        ),
        migrations.AddField(
            model_name='planconfig',
            name='daily_requests',
            field=models.PositiveIntegerField(default=3, verbose_name='Peticiones diarias (Free)'),
        ),
        migrations.AddField(
            model_name='planconfig',
            name='duration_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Duración del plan (días)'),
        ),
        migrations.AddField(
            model_name='planconfig',
            name='price_cup',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10, verbose_name='Precio del plan Premium (CUP)'),
        ),
        migrations.AddField(
            model_name='planconfig',
            name='total_requests',
            field=models.PositiveIntegerField(default=300, verbose_name='Peticiones totales (Premium)'),
        ),
        migrations.AlterField(
            model_name='planconfig',
            name='plan',
            field=models.CharField(choices=[('free', 'Gratis'), ('premium', 'Premium')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('free', 'Gratis'), ('premium', 'Premium')], default='free', max_length=10),
        ),
    ]
