# Generated by Django 5.2.3 on 2025-07-21 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_daily_exams_userprofile_daily_requests_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='¿Es pública?'),
        ),
        migrations.AddField(
            model_name='subject',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario dueño'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('name', 'subject')},
        ),
    ]
