# Generated by Django 5.2.3 on 2025-07-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_subject_is_public_subject_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='questions',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='user_answers',
            field=models.JSONField(),
        ),
    ]
